// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwas6_r97AvOGzelMc4oBC2_9KqP6go8',
    appId: '1:586926426416:web:5a334676d3160e6e7e20f5',
    messagingSenderId: '586926426416',
    projectId: 'lpi-app-bcf7c',
    authDomain: 'lpi-app-bcf7c.firebaseapp.com',
    storageBucket: 'lpi-app-bcf7c.firebasestorage.app',
    measurementId: 'G-DQVR5WLJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkfUTEMTu88gTjLzTGJSJQHi8T0m-CJk',
    appId: '1:586926426416:android:bfe1cbd197df36fa7e20f5',
    messagingSenderId: '586926426416',
    projectId: 'lpi-app-bcf7c',
    storageBucket: 'lpi-app-bcf7c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwas6_r97AvOGzelMc4oBC2_9KqP6go8',
    appId: '1:586926426416:web:cd475e93a64d75557e20f5',
    messagingSenderId: '586926426416',
    projectId: 'lpi-app-bcf7c',
    authDomain: 'lpi-app-bcf7c.firebaseapp.com',
    storageBucket: 'lpi-app-bcf7c.firebasestorage.app',
    measurementId: 'G-R5XLX2J9DW',
  );
}
